created DriveToTable
Spikes-2212-Programming-Guild/PreSeasonProject2023 pull request #15
Opened 2022-10-20 16:18 UTC by GuySabika

2022-10-20 17:35 UTC, Yoel-Perman-Brilliant requested changes

2022-10-20 17:35 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/OI.java
> +    private final XboxControllerWrapper xbox = new XboxControllerWrapper(2);
blank line

2022-10-20 17:35 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/command/DriveToTable.java
> +    private static final Supplier<Double> namespaceLeftSetPoint
not a namespace (change for the others as well)
also setpoint is one word

2022-10-20 17:35 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    public Namespace getCameraPIDNamespace() {
unnecessary

2022-10-20 17:35 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    public Supplier<Double> getkPCamera() {
remove this and the other PID constant getters, this is what the PIDSettings getter is for

2022-10-20 17:35 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    public PIDSettings getPidSettingsCamera() {
Convention A-I\a5

2022-10-20 17:35 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    public Namespace getDrivePIDNamespace() {
remove

2022-10-20 17:35 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    public Supplier<Double> getkPDrive() {
remove this and the other PID constant getters, this is what the PIDSettings getter is for

2022-10-20 17:35 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    public PIDSettings getPidSettingsDrive() {
Convention A-I\a5

2022-10-20 17:35 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    public CANSparkMax getLeft1() {
remove

2022-10-20 17:35 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    public CANSparkMax getLeft2() {
remove

2022-10-20 17:35 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    public CANSparkMax getRight1() {
remove

2022-10-20 17:35 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    public CANSparkMax getRight2() {
remove

2022-10-20 17:35 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    public Ultrasonic getUltrasonic() {
remove this, instead add getters for the necessary ultrasonic values

2022-10-20 17:35 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    public PigeonWrapper getPigeon() {
ditto

2022-10-20 17:35 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    public RelativeEncoder getLeftEncoder() {
ditto

2022-10-20 17:35 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    public RelativeEncoder getRightEncoder() {
ditto

2022-10-20 17:53 UTC, OfriRosenbaum requested changes

2022-10-20 17:53 UTC, OfriRosenbaum commented on src/main/java/frc/robot/command/DriveToTable.java
> +    private static final Supplier<Double> namespaceLeftSetPoint
setpoint is one word, remove namespace from variable name

2022-10-20 17:53 UTC, OfriRosenbaum commented on src/main/java/frc/robot/command/DriveToTable.java
> +    private static final Supplier<Double> namespaceLeftSource = namespace.addConstantDouble("left source", 0);
remove namespace from variable name

2022-10-20 17:53 UTC, OfriRosenbaum commented on src/main/java/frc/robot/command/DriveToTable.java
> +    private static final Supplier<Double> namespaceRightSource =
remove namespace from variable name

2022-10-20 17:53 UTC, OfriRosenbaum commented on src/main/java/frc/robot/command/DriveToTable.java
> +    private static final Supplier<Double> namespaceRightSetPoint
setpoint is one word, remove namespace from variable name
also put this right after the `leftSetpoint` variable

2022-10-20 17:53 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    public PIDSettings getPidSettingsCamera() {
PID should be capitalized

2022-10-20 17:53 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    public PIDSettings getPidSettingsDrive() {
PID should be capitalized

2022-10-20 18:15 UTC, Yoel-Perman-Brilliant requested changes

2022-10-20 18:15 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/command/DriveToTable.java
> +    private static final Supplier<Double> LeftSetpoint
Convention A-1\a1 (for all the others as well)
The order should be left source, right source, left setpoint, right setpoint

2022-10-22 06:52 UTC, OfriRosenbaum requested changes

2022-10-22 06:52 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    public PIDSettings getPIDSettingsDrive() {
should be `getDrivePIDSettings()`, change the variable name as well

also getters should be at the bottom of the class, just above `configureDashboard()`

can't comment on this but the suppliers for the `drivePIDSettings` are in the camera namespace instead of the drive one

2022-10-22 06:52 UTC, OfriRosenbaum commented on src/main/java/frc/robot/command/DriveToTable.java
> +            namespace.addConstantDouble("right source", 0);
you don't need the source on the shuffleboard, source should be zero (after you reset the encoders)

2022-10-22 06:52 UTC, OfriRosenbaum commented on src/main/java/frc/robot/command/DriveToTable.java
> +            = namespace.addConstantDouble("left setpoint", 0);
why do you need to split it to two lines?

2022-10-22 06:52 UTC, OfriRosenbaum commented on src/main/java/frc/robot/command/DriveToTable.java
> +            = namespace.addConstantDouble("right setpoint", 0);
why do you need to split it to two lines?

2022-10-22 06:52 UTC, OfriRosenbaum commented on src/main/java/frc/robot/command/DriveToTable.java
> +    public DriveToTable(Drivetrain drivetrain) {
this command should also reset the encoders at the `initialize()` method

2022-10-22 06:52 UTC, OfriRosenbaum commented on src/main/java/frc/robot/command/DriveToTable.java
> +    private static final Supplier<Double> leftSource = namespace.addConstantDouble("left source", 0);
you don't need the source on the shuffleboard, source should be zero (after you reset the encoders)

2022-10-22 06:52 UTC, OfriRosenbaum commented on src/main/java/frc/robot/command/DriveToTable.java
> +                rightSetpoint, leftSource, rightSource);
source should be `drivetrain::getLeftEncoder` (or right instead of left)

2022-10-22 06:53 UTC, OfriRosenbaum requested changes

2022-10-22 06:53 UTC, OfriRosenbaum commented on src/main/java/frc/robot/command/DriveToTable.java
> +    private static RootNamespace namespace = new RootNamespace("drive to table");
final

2022-10-22 08:02 UTC, merged