Photon vision
Spikes-2212-Programming-Guild/PreSeasonProject2023 pull request #16
Opened 2022-10-20 17:51 UTC by AmitBrunicki

2022-10-20 18:02 UTC, AmitBrunicki commented on src/main/java/frc/robot/Robot.java
> +import org.photonvision.PhotonCamera;
remove

2022-10-20 18:02 UTC, AmitBrunicki commented on src/main/java/frc/robot/commands/CenterOnCube.java
> +
remove this blank line

2022-10-20 18:02 UTC, AmitBrunicki commented on src/main/java/frc/robot/commands/CenterOnCube.java
> +
remove this blank line

2022-10-20 18:02 UTC, AmitBrunicki commented on src/main/java/frc/robot/commands/CenterOnTable.java
> +public class CenterOnTable extends DriveArcadeWithPID {
blank line at the start of the class

2022-10-20 18:02 UTC, AmitBrunicki commented on src/main/java/frc/robot/subsystems/Vision.java
> +    }
add a blank line after this

2022-10-20 18:02 UTC, AmitBrunicki commented on src/main/java/frc/robot/subsystems/Vision.java
> +    private static Vision instance;
should be final and separated from the other variables

2022-10-20 18:02 UTC, AmitBrunicki commented on src/main/java/frc/robot/subsystems/Vision.java
> +        super("photonvision");
call this `vision`

2022-10-20 18:02 UTC, AmitBrunicki commented on src/main/java/frc/robot/subsystems/Vision.java
> +    public double photonvisionYaw() {
getPhotonVisionYaw

2022-10-20 18:02 UTC, AmitBrunicki commented on src/main/java/frc/robot/subsystems/Vision.java
> +
remove blank line

2022-10-20 18:02 UTC, AmitBrunicki commented on src/main/java/frc/robot/subsystems/Vision.java
> +    public void configureDashboard() {
add yaw from limelight and from photon vision to this

2022-10-20 18:02 UTC, AmitBrunicki commented on vendordeps/photonlib.json
> +}
add blank line at the end of the file

2022-10-20 18:02 UTC, AmitBrunicki commented on src/main/java/frc/robot/subsystems/Vision.java
> +    public double limelightYaw(){
call this `getLimelightHorizontalOffsetFromTargetInDegrees`

2022-10-20 19:42 UTC, Yoel-Perman-Brilliant requested changes

2022-10-20 19:42 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/CenterOnCube.java
> +
remove blank line

2022-10-20 19:42 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    public PIDSettings getCameraPIDSettings() { return pidSettingsCamera; }
Convention A-II\a7

2022-10-20 19:42 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Vision.java
> +    public Vision() {
get limelight and photonCamera in the constructor and give them in `getInstance()`

2022-10-20 19:42 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Vision.java
> +    public Vision() {
private

2022-10-20 19:42 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Vision.java
> +    public double getPhotonVisionYaw() {
document

2022-10-20 19:42 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Vision.java
> +    public void setDriverMode(boolean mode) {
ditto

2022-10-20 19:42 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Vision.java
> +    public double getLimelightYaw() {
ditto

2022-10-20 19:50 UTC, Yoel-Perman-Brilliant commented
Your code doesn't compile, check why

2022-10-22 09:32 UTC, OfriRosenbaum approved these changes

2022-10-22 09:32 UTC, merged