Amit drivetrain
Spikes-2212-Programming-Guild/PreSeasonProject2023 pull request #5
Opened 2022-09-17 09:14 UTC by AmitBrunicki

2022-09-17 09:17 UTC, OfriRosenbaum requested changes

2022-09-17 09:17 UTC, OfriRosenbaum commented on src/main/java/frc/robot/OI.java
> +    Joystick left = new Joystick(0);
where private?

2022-09-17 09:17 UTC, OfriRosenbaum commented on src/main/java/frc/robot/OI.java
> +    Joystick right = new Joystick(1);
ditto

2022-09-17 09:17 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +
remove blank line

2022-09-17 10:18 UTC, OfriRosenbaum approved these changes

2022-10-01 11:57 UTC, Yoel-Perman-Brilliant requested changes

2022-10-01 11:57 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +    private final ADXRS450_Gyro gyro;
pigeon imu instead

2022-10-03 18:17 UTC, OfriRosenbaum approved these changes

2022-10-03 18:17 UTC, merged