created Claw
Spikes-2212-Programming-Guild/PreSeasonProject2023 pull request #6
Opened 2022-10-01 11:39 UTC by TurtleMinecraft

2022-10-01 12:06 UTC, OfriRosenbaum requested changes

2022-10-01 12:06 UTC, OfriRosenbaum commented on src/main/java/frc/robot/RobotMap.java
> +        int CLAW_FORWARD_SOLENOID = -1;
`CLAW_SOLENOID_FORWARD`

2022-10-01 12:06 UTC, OfriRosenbaum commented on src/main/java/frc/robot/RobotMap.java
> +        int CLAW_REVERSE_SOLENOID = -1;
`CLAW_SOLENOID_REVERSE`

2022-10-01 13:46 UTC, OfriRosenbaum requested changes

2022-10-01 13:46 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/Claw.java
> +        namespace.putData("claw solenoid forward", solenoidForward());
remove claw

2022-10-01 13:46 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/Claw.java
> +        namespace.putData("claw solenoid reverse", solenoidReverse());
ditto

2022-10-01 13:46 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/Claw.java
> +        namespace.putString("claw solenoid value", solenoid.get()::toString);
ditto

2022-10-01 13:46 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/Claw.java
> +    private Claw() {
get the solenoid and the namespace in the constructor

2022-10-01 13:47 UTC, OfriRosenbaum requested changes

2022-10-01 13:47 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/Claw.java
> +public class Claw extends DashboardedSubsystem {
add class documentation

2022-10-01 14:45 UTC, Yoel-Perman-Brilliant requested changes

2022-10-01 14:45 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Claw.java
> + * Controls the claw that is responsible for picking up cubes.
A subsystem that...

2022-10-01 14:45 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Claw.java
> +    public InstantCommand solenoidForward() {
what does it do in practice?

2022-10-01 14:45 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Claw.java
> +    public InstantCommand solenoidReverse() {
![image](https://user-images.githubusercontent.com/87820740/193414934-24bfe8b4-b62c-4925-aa39-b19dbdc3f6c0.png)

2022-10-01 15:35 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/Claw.java
> +    public InstantCommand solenoidForward() {
openSolenoid

2022-10-03 16:19 UTC, OfriRosenbaum requested changes

2022-10-03 16:19 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/Claw.java
> +        this.solenoid = solenoid;
call configureDashboard() **at the end** of the constructor

2022-10-06 13:36 UTC, OfriRosenbaum requested changes

2022-10-06 13:36 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/Claw.java
> +        namespace.putData("solenoid forward", openSolenoid());
change "solenoid forward" as well

2022-10-06 13:36 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/Claw.java
> +        namespace.putData("solenoid reverse", closeSolenoid());
ditto

2022-10-06 14:32 UTC, OfriRosenbaum requested changes

2022-10-06 14:32 UTC, OfriRosenbaum commented on src/main/java/frc/robot/commands/PickCube.java
> + * Closes the claw.
add `@see Claw`

2022-10-06 14:32 UTC, OfriRosenbaum commented on src/main/java/frc/robot/commands/DropCube.java
> + * Opens the claw.
add `@see Claw`

2022-10-06 14:32 UTC, OfriRosenbaum commented on src/main/java/frc/robot/commands/DropCube.java
> + * Opens the claw.
add why it opens (so it can drop the cubes)

2022-10-06 14:32 UTC, OfriRosenbaum commented on src/main/java/frc/robot/commands/PickCube.java
> + * Closes the claw.
add why it closes (so it can pick the cubes)

2022-10-06 14:32 UTC, OfriRosenbaum commented on src/main/java/frc/robot/commands/PickCube.java
> +        claw.openSolenoid();
supposed to be close

2022-10-06 14:32 UTC, OfriRosenbaum commented on src/main/java/frc/robot/commands/DropCube.java
> +        claw.closeSolenoid();
supposed to be open

2022-10-06 14:43 UTC, OfriRosenbaum requested changes

2022-10-06 14:43 UTC, OfriRosenbaum commented on src/main/java/frc/robot/commands/DropCube.java
> +public class DropCube extends CommandBase {
change to `InstantCommand`

2022-10-06 14:43 UTC, OfriRosenbaum commented on src/main/java/frc/robot/commands/PickCube.java
> +public class PickCube extends CommandBase {
change to `InstantCommand`

2022-10-06 15:17 UTC, OfriRosenbaum requested changes

2022-10-06 15:17 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/Claw.java
> + * Controls the claw that is responsible for picking up cubes.
holding cubes

2022-10-06 16:23 UTC, OfriRosenbaum requested changes

2022-10-06 16:23 UTC, OfriRosenbaum commented on src/main/java/frc/robot/commands/PickCube.java
> + * Closes the claw to pick cubes.
add `@see Claw`

2022-10-17 08:30 UTC, OfriRosenbaum requested changes

2022-10-17 08:30 UTC, OfriRosenbaum commented on src/main/java/frc/robot/commands/PickCube.java
>   * Closes the claw to pick cubes.
change to gripper

2022-10-17 08:30 UTC, OfriRosenbaum commented on src/main/java/frc/robot/commands/DropCube.java
>   * Opens the claw to drop cubes.
change to gripper

2022-10-17 08:30 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/Gripper.java
>   * Controls the claw that is responsible for holding cubes.
change to gripper

2022-10-17 08:30 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/Gripper.java
> +            instance = new Gripper("gripper", new DoubleSolenoid(PneumaticsModuleType.CTREPCM, RobotMap.PCM.CLAW_SOLENOID_FORWARD,
change port in `RobotMap` from claw to gripper

2022-10-17 08:30 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/Gripper.java
>                      RobotMap.PCM.CLAW_SOLENOID_REVERSE));
ditto

2022-10-17 08:30 UTC, OfriRosenbaum commented on src/main/java/frc/robot/RobotMap.java
> +        int CLAW_SOLENOID_FORWARD = -1;
change to gripper

2022-10-17 08:30 UTC, OfriRosenbaum commented on src/main/java/frc/robot/RobotMap.java
> +        int CLAW_SOLENOID_REVERSE = -1;
change to gripper

2022-10-17 09:02 UTC, OfriRosenbaum requested changes

2022-10-17 09:02 UTC, OfriRosenbaum commented on src/main/java/frc/robot/commands/CloseGripper.java
> +        addRequirements((Subsystem) gripper);
remove casting

2022-10-17 09:02 UTC, OfriRosenbaum commented on src/main/java/frc/robot/commands/OpenGripper.java
> +        addRequirements((Subsystem) gripper);
remove casting

2022-10-20 17:39 UTC, Yoel-Perman-Brilliant requested changes

2022-10-20 17:39 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/CloseGripper.java
> + * Closes the gripper to pick cubes.
pick up

2022-10-22 07:25 UTC, OfriRosenbaum approved these changes

2022-10-22 07:25 UTC, OfriRosenbaum requested changes
add spikeslib2 folder and fix conflict

2022-10-22 08:08 UTC, merged