Amit climber
Spikes-2212-Programming-Guild/PreSeasonProject2023 pull request #9
Opened 2022-10-01 14:06 UTC by AmitBrunicki

2022-10-01 14:13 UTC, OfriRosenbaum requested changes

2022-10-01 14:13 UTC, OfriRosenbaum commented on src/main/java/frc/robot/OI.java
> +    private Joystick left = new Joystick(0);
delete the content of this class

2022-10-01 14:13 UTC, OfriRosenbaum commented on src/main/java/frc/robot/Robot.java
> +import com.spikes2212.command.drivetrains.commands.DriveArcade;
delete this import

2022-10-01 14:13 UTC, OfriRosenbaum commented on src/main/java/frc/robot/RobotMap.java
> +        int CLIMBER_FRONT_SOLENOID_1_FORWARD = -1;
order this by a set of forward and reverse for each solenoid (forward1, reverse1, forward2, reverse2...)

2022-10-01 14:13 UTC, OfriRosenbaum commented on src/main/java/frc/robot/OI.java
> +import edu.wpi.first.wpilibj.Joystick;
remove this import

2022-10-01 14:13 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/Climber.java
> +public class Climber extends DashboardedSubsystem {
`CTRL + ALT + L` if needed

2022-10-01 14:13 UTC, OfriRosenbaum commented on src/main/java/frc/robot/RobotMap.java
> +        int CLIMBER_FRONT_SOLENOID_1_FORWARD = -1;
also, it is called reverse, not backword

2022-10-01 14:13 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/Climber.java
> +        namespace.putData("front solenoids backword", frontSolenoidsOff());
reverse, not backword

2022-10-01 14:13 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/Climber.java
> +        namespace.putData("back solenoids backword", backSolenoidOff());
ditto

2022-10-01 14:13 UTC, OfriRosenbaum requested changes

2022-10-01 14:13 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/Climber.java
> +public class Climber extends DashboardedSubsystem {
add class documentation

2022-10-01 14:13 UTC, AmitBrunicki commented on src/main/java/frc/robot/OI.java
> +    private Joystick left = new Joystick(0);
OK

2022-10-01 14:15 UTC, AmitBrunicki commented on src/main/java/frc/robot/Robot.java
> +import com.spikes2212.command.drivetrains.commands.DriveArcade;
OK

2022-10-01 14:20 UTC, AmitBrunicki commented on src/main/java/frc/robot/RobotMap.java
> +        int CLIMBER_FRONT_SOLENOID_1_FORWARD = -1;
OK

2022-10-01 14:22 UTC, AmitBrunicki commented on src/main/java/frc/robot/subsystems/Climber.java
> +public class Climber extends DashboardedSubsystem {
Nooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

2022-10-01 15:07 UTC, Yoel-Perman-Brilliant requested changes

2022-10-01 15:07 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/OI.java
> +import edu.wpi.first.wpilibj.Joystick;
remove this import

2022-10-01 15:07 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/RobotMap.java
> +        int DRIVETRAIN_LEFT_SPARKMAX_1 = -1;
delete

2022-10-01 15:07 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/RobotMap.java
> +        int DRIVETRAIN_LEFT_SPARKMAX_2 = -1;
ditto

2022-10-01 15:07 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/RobotMap.java
> +        int DRIVETRAIN_RIGHT_SPARKMAX_1 = -1;
ditto

2022-10-01 15:07 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/RobotMap.java
> +        int DRIVETRAIN_RIGHT_SPARKMAX_2 = -1;
ditto

2022-10-01 15:07 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Climber.java
> + * Controls the three {@link DoubleSolenoid}s that make the robot climb.
A subsystem that..

2022-10-01 15:07 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Climber.java
> +        if (instance == null)
add curly braces

2022-10-01 15:07 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Climber.java
> +    private Climber(String name, DoubleSolenoid frontSolenoid1, DoubleSolenoid frontSolenoid2, DoubleSolenoid backSolenoid) {
namespaceName

2022-10-01 15:07 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Climber.java
> +    public InstantCommand backSolenoidOn() {
![image](https://user-images.githubusercontent.com/87820740/193415543-bf884799-90a0-4e1d-bdfe-6008b9cbd278.png)

2022-10-01 15:07 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Climber.java
> +    public InstantCommand backSolenoidOff() {
![image](https://user-images.githubusercontent.com/87820740/193415548-75873333-c77e-49f6-bb4c-e62afc0a31f4.png)

2022-10-01 15:07 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Climber.java
> +    public InstantCommand frontSolenoidsOn() {
change to `openFrontSolenoids()`

2022-10-01 15:07 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Climber.java
> +    public InstantCommand frontSolenoidsOff() {
change to `closeFrontSolenoids()`

2022-10-01 15:07 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Climber.java
> +        namespace.putData("front solenoids forward", frontSolenoidsOn());
change to `open front solenoids`

2022-10-01 15:07 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Climber.java
> +        namespace.putString("front solenoid 1 value", frontSolenoid1.get()::toString);
this should potentially change to lambda expression, not sure yet

2022-10-20 17:20 UTC, Yoel-Perman-Brilliant requested changes

2022-10-20 17:20 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/Climb.java
> +    private static final Supplier<Double> OPEN_FRONT_SOLENOID_ULTRASONIC_DISTANCE =
units

2022-10-20 17:20 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/Climb.java
> +    private static final Supplier<Double> OPEN_BACK_SOLENOID_ULTRASONIC_DISTANCE =
ditto

2022-10-20 17:20 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/Climb.java
> +    private static final Supplier<Double> CLOSE_BACK_SOLENOID_ULTRASONIC_DISTANCE =
ditto

2022-10-20 17:20 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/Climb.java
> +    public Climb() {
accept subsystems in constructor, it's more solid

2022-10-20 17:20 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/Climb.java
> +                backAwayFromHab(drivetrain),
First of all, it's hub. Second of all, it should be deck.

2022-10-20 17:20 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/Climb.java
> +    private InstantCommand openFrontSolenoid(Climber climber) {
unnecessary

2022-10-20 17:20 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/Climb.java
> +    private InstantCommand openBackSolenoid(Climber climber) {
ditto

2022-10-20 17:20 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/Climb.java
> +    private InstantCommand closeFrontSolenoid(Climber climber) {
ditto

2022-10-20 17:20 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/Climb.java
> +    private InstantCommand closeBackSolenoid(Climber climber) {
ditto

2022-10-20 17:20 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/Climb.java
> +    private static final Supplier<Double> OPEN_FRONT_SOLENOID_ULTRASONIC_DISTANCE =
also document (the other constants too)

2022-10-20 17:20 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Climber.java
> +    public InstantCommand openBackSolenoids() {
solenoid, not solenoids

2022-10-20 17:20 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Climber.java
> +    public InstantCommand closeBackSolenoids() {
ditto

2022-10-20 17:20 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Climber.java
> +        namespace.putData("front solenoids forward", openFrontSolenoids());
`open front solenoids`
change for the others too

2022-10-20 17:20 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/Climber.java
> +        namespace.putData("back solenoids forward", openBackSolenoids());
it's one solenoid

2022-10-22 07:04 UTC, OfriRosenbaum requested changes

2022-10-22 07:04 UTC, OfriRosenbaum commented on src/main/java/frc/robot/commands/Climb.java
> +            namespace.addConstantDouble("open front solenoid ultrasonic in cm", 50);
add a blank line after this line

2022-10-22 07:04 UTC, OfriRosenbaum commented on src/main/java/frc/robot/commands/Climb.java
> +            namespace.addConstantDouble("open back solenoid ultrasonic in cm", 30);
add a blank line after this line

2022-10-22 07:04 UTC, OfriRosenbaum commented on src/main/java/frc/robot/commands/Climb.java
> +            namespace.addConstantDouble("close back solenoid ultrasonic in cm", 15);
add a blank line after this line

2022-10-22 07:04 UTC, OfriRosenbaum commented on src/main/java/frc/robot/commands/Climb.java
> +     * The amount of centimeters that the robot is allowed to miss the target range by.
remove the word range, and change to `the maximum amount...`

2022-10-22 07:35 UTC, OfriRosenbaum requested changes

2022-10-22 07:35 UTC, OfriRosenbaum commented on src/main/java/frc/robot/commands/Climb.java
> +     * The distance from the deck in which the {@link Climber} front solenoid needs to open.
there are two front solenoids, so solenoid should solenoids (and needs should be need)

2022-10-22 07:35 UTC, OfriRosenbaum commented on src/main/java/frc/robot/commands/Climb.java
> +    private static final Supplier<Double> OPEN_FRONT_SOLENOID_ULTRASONIC_IN_CM =
there are two front solenoids, so solenoid should solenoids

2022-10-22 07:35 UTC, OfriRosenbaum commented on src/main/java/frc/robot/commands/Climb.java
> +            namespace.addConstantDouble("open front solenoid ultrasonic in cm", 50);
there are two front solenoids, so solenoid should solenoids

2022-10-22 07:39 UTC, OfriRosenbaum approved these changes

2022-10-22 07:39 UTC, merged